In [1]:
import networkx as nx
import osmnx as ox
from IPython.display import IFrame
import geopandas as gdp
import numpy as np
import pandas as pd

%matplotlib inline
ox.__version__

'1.2.2'

In [76]:
# downloding the street network
place = "Trier, Germany"
#cf = '["highway"~"motorway"]'
#cf =  '["highway"~"primary"]'
#G = ox.graph_from_place("Trier, Germany", network_type= "drive") ### graph of the given city
G = ox.graph_from_place(place, network_type="drive")

In [3]:
# plot the street network with folium

m1 = ox.plot_graph_folium(G, popup_attribute="name", weight = 2, color = "#8b0000")

In [ ]:
filepath = r'C:\Users\looka\OneDrive\Desktop\RCS\graph.html'
m1.save(filepath)
IFrame(filepath, width=600, height = 500)

In [5]:
print(G)

MultiDiGraph with 2737 nodes and 6231 edges

In [6]:
# use networkX to calculate the shortest path between two nodes

origin_node = list(G.nodes())[0]
destination_node = list(G.nodes())[-1]

route = nx.shortest_path(G, origin_node, destination_node)

In [ ]:
# plot the route with folium
# like above, you can pass keyword args along to folium PolyLine to style the lines

m2 = ox.plot_route_folium(G, route, weight = 10)
filepath = r'C:\Users\looka\OneDrive\Desktop\RCS\route.html'
m2.save(filepath)
IFrame(filepath, width=600, height = 500)

In [ ]:
orig = ox.distance.nearest_nodes(G, X = 6.639066, Y = 49.751096) # saarstraße
dest = ox.distance.nearest_nodes(G, X = 6.628289, Y = 49.751833) # germanstraße, gervasiusstraße
route = ox.shortest_path(G, orig, dest, weight = "travel_time")
m3 = ox.plot_route_folium(G, route, weight=10)
filepath = r'C:\Users\looka\OneDrive\Desktop\RCS\shortest_1.html'
m3.save(filepath)
IFrame(filepath, width=600, height = 500)

In [9]:
print(orig)
print(dest)

268656889
60365100

In [10]:
route[0]

268656889

In [11]:
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

node_df = gdp.GeoDataFrame()
edge_df = gdp.GeoDataFrame()
for i in route:
    print(i)
    node_df = node_df.append(gdf_nodes.loc[[i]])
    edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])

268656889

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])

1428980932
1428980910
322854916
322854921
10602410
10602396
3328610208

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append(gdf_nodes.loc[[i]])

3328610215
3328610218
20909587
206265755
206178456
60365099
60365100

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3064609582.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])

In [12]:
len(node_df) - 1

14

In [13]:
edge_df

                                            osmid  oneway   lanes  \
u          v          key
268656889  20909623   0                   6073629    True     NaN
           1428980932 0                  22959075   False     NaN
1428980932 20909627   0                  22959075   False     NaN
           1428980910 0                 129534324   False     NaN
           268656889  0                  22959075   False     NaN
1428980910 1428980932 0                 129534324   False     NaN
           322854916  0                 461707736   False     NaN
           268656888  0                 608044009   False     NaN
322854916  1428980910 0                 461707736   False     NaN
           322854921  0    [928536690, 814112811]   False       2
           3325983705 0                 814112811   False       2
322854921  268656901  0                  24718036   False     NaN
           10602410   0                 329619113   False     NaN
           322854916  0    [928536690, 814112811]   False       2
10602410   3212415597 0                   6073363   False     NaN
           10602396   0     [348744826, 44181036]    True       3
           322854921  0                 329619113   False     NaN
10602396   268656889  0      [620480498, 6073765]    True       1
           3328610208 0                  44503497    True     NaN
           20909583   0                 113363975    True       1
3328610208 3328610212 0                 326240046    True     NaN
           3328610215 0                 484936170    True     NaN
3328610215 3328610218 0                 449537987    True     NaN
           3328610212 0                 348744824    True     NaN
3328610218 20909586   0                   6073647    True       2
           20909587   0     [396347959, 43176479]    True  [2, 3]
20909587   1620783442 0     [201864952, 23323565]   False       2
           206265755  0    [793427594, 161279663]    True       3
206265755  206178456  0                 391065024    True       3
206178456  206178458  0                  19789570    True       1
           60365099   0                 391065027    True       3
60365099   60365459   0                 396347958    True       2
           60365100   0                 177395531    True       2
60365100   20834070   0                  39177136    True       1
           300014888  0                  44841066    True       2

                                                name  \
u          v          key
268656889  20909623   0              Gervasiusstraße
           1428980932 0                Wechselstraße
1428980932 20909627   0                Wechselstraße
           1428980910 0                 Kuhnenstraße
           268656889  0                Wechselstraße
1428980910 1428980932 0                 Kuhnenstraße
           322854916  0                 Kuhnenstraße
           268656888  0                 Kuhnenstraße
322854916  1428980910 0                 Kuhnenstraße
           322854921  0                    Weberbach
           3325983705 0                    Weberbach
322854921  268656901  0                    Graugasse
           10602410   0                    Weberbach
           322854916  0                    Weberbach
10602410   3212415597 0                          NaN
           10602396   0                 Kaiserstraße
           322854921  0                    Weberbach
10602396   268656889  0    [Germanstraße, Neustraße]
           3328610208 0                 Kaiserstraße
           20909583   0                          NaN
3328610208 3328610212 0           Gerty-Spies-Straße
           3328610215 0                 Kaiserstraße
3328610215 3328610218 0                 Kaiserstraße
           3328610212 0           Gerty-Spies-Straße
3328610218 20909586   0                          NaN
           20909587   0                 Kaiserstraße
20909587   1620783442 0        Lorenz-Kellner-Straße
           206265755  0                 Kaiserstraße
206265755  206178456  0                 Kaiserstraße
206178456  206178458  0                          NaN
           60365099   0                 Kaiserstraße
60365099   60365459   0                 Kaiserstraße
           60365100   0               Johanniterufer
60365100   20834070   0             Karl-Marx-Straße
           300014888  0               Johanniterufer

                                                highway reversed   length  \
u          v          key
268656889  20909623   0                     residential    False   92.770
           1428980932 0                   living_street    False   61.715
1428980932 20909627   0                   living_street    False   20.646
           1428980910 0                   living_street    False   44.524
           268656889  0                   living_street     True   61.715
1428980910 1428980932 0                   living_street     True   44.524
           322854916  0                   living_street     True   64.006
           268656888  0                     residential    False   58.245
322854916  1428980910 0                   living_street    False   64.006
           322854921  0                     residential    False   37.408
           3325983705 0                     residential     True   48.905
322854921  268656901  0                   living_street     True  125.374
           10602410   0                     residential    False   47.082
           322854916  0                     residential     True   37.408
10602410   3212415597 0                     residential    False   28.040
           10602396   0                       secondary    False  219.652
           322854921  0                     residential     True   47.082
10602396   268656889  0    [residential, living_street]    False  249.956
           3328610208 0                       secondary    False  153.907
           20909583   0                  secondary_link    False   36.470
3328610208 3328610212 0                     residential    False   30.219
           3328610215 0                       secondary    False   24.475
3328610215 3328610218 0                       secondary    False   11.676
           3328610212 0                     residential    False   19.963
3328610218 20909586   0                     residential    False   45.665
           20909587   0                       secondary    False  232.150
20909587   1620783442 0                     residential    False  132.964
           206265755  0                       secondary    False  144.406
206265755  206178456  0                       secondary    False   65.492
206178456  206178458  0                  secondary_link    False   42.055
           60365099   0                       secondary    False   24.128
60365099   60365459   0                       secondary    False   12.063
           60365100   0                         primary    False   59.961
60365100   20834070   0                    unclassified    False   11.915
           300014888  0                         primary    False  106.307

                          maxspeed  \
u          v          key
268656889  20909623   0         50
           1428980932 0        NaN
1428980932 20909627   0        NaN
           1428980910 0        NaN
           268656889  0        NaN
1428980910 1428980932 0        NaN
           322854916  0        NaN
           268656888  0        NaN
322854916  1428980910 0        NaN
           322854921  0         50
           3325983705 0         50
322854921  268656901  0        NaN
           10602410   0         50
           322854916  0         50
10602410   3212415597 0        NaN
           10602396   0         50
           322854921  0         50
10602396   268656889  0         50
           3328610208 0         50
           20909583   0         50
3328610208 3328610212 0        NaN
           3328610215 0         50
3328610215 3328610218 0         50
           3328610212 0        NaN
3328610218 20909586   0         50
           20909587   0         50
20909587   1620783442 0        NaN
           206265755  0         50
206265755  206178456  0         50
206178456  206178458  0         50
           60365099   0         50
60365099   60365459   0         50
           60365100   0         50
60365100   20834070   0         50
           300014888  0         50

                                                                    geometry  \
u          v          key
268656889  20909623   0    LINESTRING (6.63906 49.75107, 6.63913 49.75115...
           1428980932 0    LINESTRING (6.63906 49.75107, 6.63911 49.75103...
1428980932 20909627   0      LINESTRING (6.63983 49.75084, 6.64010 49.75079)
           1428980910 0      LINESTRING (6.63983 49.75084, 6.63964 49.75046)
           268656889  0    LINESTRING (6.63983 49.75084, 6.63940 49.75093...
1428980910 1428980932 0      LINESTRING (6.63964 49.75046, 6.63983 49.75084)
           322854916  0    LINESTRING (6.63964 49.75046, 6.64028 49.75029...
           268656888  0    LINESTRING (6.63964 49.75046, 6.63960 49.75047...
322854916  1428980910 0    LINESTRING (6.64047 49.75025, 6.64035 49.75027...
           322854921  0    LINESTRING (6.64047 49.75025, 6.64044 49.75019...
           3325983705 0    LINESTRING (6.64047 49.75025, 6.64058 49.75047...
322854921  268656901  0    LINESTRING (6.64033 49.74993, 6.64019 49.74994...
           10602410   0    LINESTRING (6.64033 49.74993, 6.64022 49.74969...
           322854916  0    LINESTRING (6.64033 49.74993, 6.64044 49.75019...
10602410   3212415597 0    LINESTRING (6.64015 49.74952, 6.64008 49.74938...
           10602396   0    LINESTRING (6.64015 49.74952, 6.64005 49.74955...
           322854921  0    LINESTRING (6.64015 49.74952, 6.64020 49.74964...
10602396   268656889  0    LINESTRING (6.63723 49.75009, 6.63724 49.75015...
           3328610208 0    LINESTRING (6.63723 49.75009, 6.63711 49.75012...
           20909583   0    LINESTRING (6.63723 49.75009, 6.63717 49.75006...
3328610208 3328610212 0    LINESTRING (6.63514 49.75040, 6.63502 49.75046...
           3328610215 0    LINESTRING (6.63514 49.75040, 6.63495 49.75043...
3328610215 3328610218 0      LINESTRING (6.63481 49.75045, 6.63465 49.75047)
           3328610212 0    LINESTRING (6.63481 49.75045, 6.63483 49.75049...
3328610218 20909586   0    LINESTRING (6.63465 49.75047, 6.63460 49.75044...
           20909587   0    LINESTRING (6.63465 49.75047, 6.63439 49.75050...
20909587   1620783442 0    LINESTRING (6.63148 49.75089, 6.63152 49.75096...
           206265755  0    LINESTRING (6.63148 49.75089, 6.63136 49.75090...
206265755  206178456  0    LINESTRING (6.62952 49.75116, 6.62929 49.75118...
206178456  206178458  0    LINESTRING (6.62862 49.75128, 6.62854 49.75123...
           60365099   0    LINESTRING (6.62862 49.75128, 6.62843 49.75130...
60365099   60365459   0      LINESTRING (6.62829 49.75129, 6.62814 49.75124)
           60365100   0    LINESTRING (6.62829 49.75129, 6.62829 49.75134...
60365100   20834070   0      LINESTRING (6.62827 49.75183, 6.62810 49.75181)
           300014888  0    LINESTRING (6.62827 49.75183, 6.62827 49.75188...

                             ref width bridge junction access tunnel
u          v          key
268656889  20909623   0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980932 0      NaN   NaN    NaN      NaN    NaN    NaN
1428980932 20909627   0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980910 0      NaN   NaN    NaN      NaN    NaN    NaN
           268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
1428980910 1428980932 0      NaN   NaN    NaN      NaN    NaN    NaN
           322854916  0      NaN   NaN    NaN      NaN    NaN    NaN
           268656888  0      NaN   NaN    NaN      NaN    NaN    NaN
322854916  1428980910 0      NaN   NaN    NaN      NaN    NaN    NaN
           322854921  0      NaN   NaN    NaN      NaN    NaN    NaN
           3325983705 0      NaN   NaN    NaN      NaN    NaN    NaN
322854921  268656901  0      NaN   NaN    NaN      NaN    NaN    NaN
           10602410   0      NaN   NaN    NaN      NaN    NaN    NaN
           322854916  0      NaN   NaN    NaN      NaN    NaN    NaN
10602410   3212415597 0      NaN   NaN    NaN      NaN    NaN    NaN
           10602396   0    L 143   NaN    NaN      NaN    NaN    NaN
           322854921  0      NaN   NaN    NaN      NaN    NaN    NaN
10602396   268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
           3328610208 0    L 143   NaN    NaN      NaN    NaN    NaN
           20909583   0      NaN   NaN    NaN      NaN    NaN    NaN
3328610208 3328610212 0      NaN   NaN    NaN      NaN    NaN    NaN
           3328610215 0    L 143   NaN    NaN      NaN    NaN    NaN
3328610215 3328610218 0    L 143   NaN    NaN      NaN    NaN    NaN
           3328610212 0      NaN   NaN    NaN      NaN    NaN    NaN
3328610218 20909586   0      NaN   NaN    NaN      NaN    NaN    NaN
           20909587   0    L 143   NaN    NaN      NaN    NaN    NaN
20909587   1620783442 0      NaN   NaN    NaN      NaN    NaN    NaN
           206265755  0    L 143   NaN    NaN      NaN    NaN    NaN
206265755  206178456  0    L 143   NaN    NaN      NaN    NaN    NaN
206178456  206178458  0      NaN   NaN    NaN      NaN    NaN    NaN
           60365099   0    L 143   NaN    NaN      NaN    NaN    NaN
60365099   60365459   0    L 143   NaN    NaN      NaN    NaN    NaN
           60365100   0     B 49   NaN    NaN      NaN    NaN    NaN
60365100   20834070   0      NaN   NaN    NaN      NaN    NaN    NaN
           300014888  0     B 49   NaN    NaN      NaN    NaN    NaN

In [14]:
gdf_edges.loc[(60365099, slice(None), slice(None)),:]

                           osmid  oneway lanes            name    highway  \
u        v        key
60365099 60365459 0    396347958    True     2    Kaiserstraße  secondary
         60365100 0    177395531    True     2  Johanniterufer    primary

                      reversed  length maxspeed  \
u        v        key
60365099 60365459 0      False  12.063       50
         60365100 0      False  59.961       50

                                                                geometry  \
u        v        key
60365099 60365459 0      LINESTRING (6.62829 49.75129, 6.62814 49.75124)
         60365100 0    LINESTRING (6.62829 49.75129, 6.62829 49.75134...

                         ref width bridge junction access tunnel
u        v        key
60365099 60365459 0    L 143   NaN    NaN      NaN    NaN    NaN
         60365100 0     B 49   NaN    NaN      NaN    NaN    NaN

In [15]:
gdf_edges.loc[(60365099, 60365100, slice(None)),:]

,,,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry,ref,width,bridge,junction,access,tunnel
u,v,key,,,,,,,,,,,,,,,
60365099,60365100,0,177395531,True,2,Johanniterufer,primary,False,59.961,50,"LINESTRING (6.62829 49.75129, 6.62829 49.75134...",B 49,NaN,NaN,NaN,NaN,NaN

In [ ]:
gdf_edges

In [17]:
gdf_edges.index.names

FrozenList(['u', 'v', 'key'])

In [18]:
gdf_edges.index.values

array([(10602396, 268656889, 0), (10602396, 3328610208, 0),
       (10602396, 20909583, 0), ..., (9856202107, 3755316673, 0),
       (9888516440, 4450647438, 0), (9888516440, 4690637729, 0)],
      dtype=object)

In [21]:
gdf_edges.loc[(10602396, slice(None), slice(None)),:]

                                        osmid  oneway lanes  \
u        v          key
10602396 268656889  0    [620480498, 6073765]    True     1
         3328610208 0                44503497    True   NaN
         20909583   0               113363975    True     1

                                              name  \
u        v          key
10602396 268656889  0    [Germanstraße, Neustraße]
         3328610208 0                 Kaiserstraße
         20909583   0                          NaN

                                              highway reversed   length  \
u        v          key
10602396 268656889  0    [residential, living_street]    False  249.956
         3328610208 0                       secondary    False  153.907
         20909583   0                  secondary_link    False   36.470

                        maxspeed  \
u        v          key
10602396 268656889  0         50
         3328610208 0         50
         20909583   0         50

                                                                  geometry  \
u        v          key
10602396 268656889  0    LINESTRING (6.63723 49.75009, 6.63724 49.75015...
         3328610208 0    LINESTRING (6.63723 49.75009, 6.63711 49.75012...
         20909583   0    LINESTRING (6.63723 49.75009, 6.63717 49.75006...

                           ref width bridge junction access tunnel
u        v          key
10602396 268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
         3328610208 0    L 143   NaN    NaN      NaN    NaN    NaN
         20909583   0      NaN   NaN    NaN      NaN    NaN    NaN

In [ ]:
df_edge = gdp.GeoDataFrame()
for i in route:
    df_edge = df_edge.append(gdf_edges.loc[[i]])

In [93]:
df_edge

                                            osmid  oneway   lanes  \
u          v          key
268656889  20909623   0                   6073629    True     NaN
           1428980932 0                  22959075   False     NaN
1428980932 20909627   0                  22959075   False     NaN
           1428980910 0                 129534324   False     NaN
           268656889  0                  22959075   False     NaN
1428980910 1428980932 0                 129534324   False     NaN
           322854916  0                 461707736   False     NaN
           268656888  0                 608044009   False     NaN
322854916  1428980910 0                 461707736   False     NaN
           322854921  0    [928536690, 814112811]   False       2
           3325983705 0                 814112811   False       2
322854921  268656901  0                  24718036   False     NaN
           10602410   0                 329619113   False     NaN
           322854916  0    [928536690, 814112811]   False       2
10602410   3212415597 0                   6073363   False     NaN
           10602396   0     [348744826, 44181036]    True       3
           322854921  0                 329619113   False     NaN
10602396   268656889  0      [620480498, 6073765]    True       1
           3328610208 0                  44503497    True     NaN
           20909583   0                 113363975    True       1
3328610208 3328610212 0                 326240046    True     NaN
           3328610215 0                 484936170    True     NaN
3328610215 3328610218 0                 449537987    True     NaN
           3328610212 0                 348744824    True     NaN
3328610218 20909586   0                   6073647    True       2
           20909587   0     [396347959, 43176479]    True  [2, 3]
20909587   1620783442 0     [201864952, 23323565]   False       2
           206265755  0    [793427594, 161279663]    True       3
206265755  206178456  0                 391065024    True       3
206178456  206178458  0                  19789570    True       1
           60365099   0                 391065027    True       3
60365099   60365459   0                 396347958    True       2
           60365100   0                 177395531    True       2
60365100   20834070   0                  39177136    True       1
           300014888  0                  44841066    True       2

                                                name  \
u          v          key
268656889  20909623   0              Gervasiusstraße
           1428980932 0                Wechselstraße
1428980932 20909627   0                Wechselstraße
           1428980910 0                 Kuhnenstraße
           268656889  0                Wechselstraße
1428980910 1428980932 0                 Kuhnenstraße
           322854916  0                 Kuhnenstraße
           268656888  0                 Kuhnenstraße
322854916  1428980910 0                 Kuhnenstraße
           322854921  0                    Weberbach
           3325983705 0                    Weberbach
322854921  268656901  0                    Graugasse
           10602410   0                    Weberbach
           322854916  0                    Weberbach
10602410   3212415597 0                          NaN
           10602396   0                 Kaiserstraße
           322854921  0                    Weberbach
10602396   268656889  0    [Germanstraße, Neustraße]
           3328610208 0                 Kaiserstraße
           20909583   0                          NaN
3328610208 3328610212 0           Gerty-Spies-Straße
           3328610215 0                 Kaiserstraße
3328610215 3328610218 0                 Kaiserstraße
           3328610212 0           Gerty-Spies-Straße
3328610218 20909586   0                          NaN
           20909587   0                 Kaiserstraße
20909587   1620783442 0        Lorenz-Kellner-Straße
           206265755  0                 Kaiserstraße
206265755  206178456  0                 Kaiserstraße
206178456  206178458  0                          NaN
           60365099   0                 Kaiserstraße
60365099   60365459   0                 Kaiserstraße
           60365100   0               Johanniterufer
60365100   20834070   0             Karl-Marx-Straße
           300014888  0               Johanniterufer

                                                highway reversed   length  \
u          v          key
268656889  20909623   0                     residential    False   92.770
           1428980932 0                   living_street    False   61.715
1428980932 20909627   0                   living_street    False   20.646
           1428980910 0                   living_street    False   44.524
           268656889  0                   living_street     True   61.715
1428980910 1428980932 0                   living_street     True   44.524
           322854916  0                   living_street     True   64.006
           268656888  0                     residential    False   58.245
322854916  1428980910 0                   living_street    False   64.006
           322854921  0                     residential    False   37.408
           3325983705 0                     residential     True   48.905
322854921  268656901  0                   living_street     True  125.374
           10602410   0                     residential    False   47.082
           322854916  0                     residential     True   37.408
10602410   3212415597 0                     residential    False   28.040
           10602396   0                       secondary    False  219.652
           322854921  0                     residential     True   47.082
10602396   268656889  0    [residential, living_street]    False  249.956
           3328610208 0                       secondary    False  153.907
           20909583   0                  secondary_link    False   36.470
3328610208 3328610212 0                     residential    False   30.219
           3328610215 0                       secondary    False   24.475
3328610215 3328610218 0                       secondary    False   11.676
           3328610212 0                     residential    False   19.963
3328610218 20909586   0                     residential    False   45.665
           20909587   0                       secondary    False  232.150
20909587   1620783442 0                     residential    False  132.964
           206265755  0                       secondary    False  144.406
206265755  206178456  0                       secondary    False   65.492
206178456  206178458  0                  secondary_link    False   42.055
           60365099   0                       secondary    False   24.128
60365099   60365459   0                       secondary    False   12.063
           60365100   0                         primary    False   59.961
60365100   20834070   0                    unclassified    False   11.915
           300014888  0                         primary    False  106.307

                          maxspeed  \
u          v          key
268656889  20909623   0         50
           1428980932 0        NaN
1428980932 20909627   0        NaN
           1428980910 0        NaN
           268656889  0        NaN
1428980910 1428980932 0        NaN
           322854916  0        NaN
           268656888  0        NaN
322854916  1428980910 0        NaN
           322854921  0         50
           3325983705 0         50
322854921  268656901  0        NaN
           10602410   0         50
           322854916  0         50
10602410   3212415597 0        NaN
           10602396   0         50
           322854921  0         50
10602396   268656889  0         50
           3328610208 0         50
           20909583   0         50
3328610208 3328610212 0        NaN
           3328610215 0         50
3328610215 3328610218 0         50
           3328610212 0        NaN
3328610218 20909586   0         50
           20909587   0         50
20909587   1620783442 0        NaN
           206265755  0         50
206265755  206178456  0         50
206178456  206178458  0         50
           60365099   0         50
60365099   60365459   0         50
           60365100   0         50
60365100   20834070   0         50
           300014888  0         50

                                                                    geometry  \
u          v          key
268656889  20909623   0    LINESTRING (6.63906 49.75107, 6.63913 49.75115...
           1428980932 0    LINESTRING (6.63906 49.75107, 6.63911 49.75103...
1428980932 20909627   0      LINESTRING (6.63983 49.75084, 6.64010 49.75079)
           1428980910 0      LINESTRING (6.63983 49.75084, 6.63964 49.75046)
           268656889  0    LINESTRING (6.63983 49.75084, 6.63940 49.75093...
1428980910 1428980932 0      LINESTRING (6.63964 49.75046, 6.63983 49.75084)
           322854916  0    LINESTRING (6.63964 49.75046, 6.64028 49.75029...
           268656888  0    LINESTRING (6.63964 49.75046, 6.63960 49.75047...
322854916  1428980910 0    LINESTRING (6.64047 49.75025, 6.64035 49.75027...
           322854921  0    LINESTRING (6.64047 49.75025, 6.64044 49.75019...
           3325983705 0    LINESTRING (6.64047 49.75025, 6.64058 49.75047...
322854921  268656901  0    LINESTRING (6.64033 49.74993, 6.64019 49.74994...
           10602410   0    LINESTRING (6.64033 49.74993, 6.64022 49.74969...
           322854916  0    LINESTRING (6.64033 49.74993, 6.64044 49.75019...
10602410   3212415597 0    LINESTRING (6.64015 49.74952, 6.64008 49.74938...
           10602396   0    LINESTRING (6.64015 49.74952, 6.64005 49.74955...
           322854921  0    LINESTRING (6.64015 49.74952, 6.64020 49.74964...
10602396   268656889  0    LINESTRING (6.63723 49.75009, 6.63724 49.75015...
           3328610208 0    LINESTRING (6.63723 49.75009, 6.63711 49.75012...
           20909583   0    LINESTRING (6.63723 49.75009, 6.63717 49.75006...
3328610208 3328610212 0    LINESTRING (6.63514 49.75040, 6.63502 49.75046...
           3328610215 0    LINESTRING (6.63514 49.75040, 6.63495 49.75043...
3328610215 3328610218 0      LINESTRING (6.63481 49.75045, 6.63465 49.75047)
           3328610212 0    LINESTRING (6.63481 49.75045, 6.63483 49.75049...
3328610218 20909586   0    LINESTRING (6.63465 49.75047, 6.63460 49.75044...
           20909587   0    LINESTRING (6.63465 49.75047, 6.63439 49.75050...
20909587   1620783442 0    LINESTRING (6.63148 49.75089, 6.63152 49.75096...
           206265755  0    LINESTRING (6.63148 49.75089, 6.63136 49.75090...
206265755  206178456  0    LINESTRING (6.62952 49.75116, 6.62929 49.75118...
206178456  206178458  0    LINESTRING (6.62862 49.75128, 6.62854 49.75123...
           60365099   0    LINESTRING (6.62862 49.75128, 6.62843 49.75130...
60365099   60365459   0      LINESTRING (6.62829 49.75129, 6.62814 49.75124)
           60365100   0    LINESTRING (6.62829 49.75129, 6.62829 49.75134...
60365100   20834070   0      LINESTRING (6.62827 49.75183, 6.62810 49.75181)
           300014888  0    LINESTRING (6.62827 49.75183, 6.62827 49.75188...

                             ref width bridge junction access tunnel
u          v          key
268656889  20909623   0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980932 0      NaN   NaN    NaN      NaN    NaN    NaN
1428980932 20909627   0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980910 0      NaN   NaN    NaN      NaN    NaN    NaN
           268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
1428980910 1428980932 0      NaN   NaN    NaN      NaN    NaN    NaN
           322854916  0      NaN   NaN    NaN      NaN    NaN    NaN
           268656888  0      NaN   NaN    NaN      NaN    NaN    NaN
322854916  1428980910 0      NaN   NaN    NaN      NaN    NaN    NaN
           322854921  0      NaN   NaN    NaN      NaN    NaN    NaN
           3325983705 0      NaN   NaN    NaN      NaN    NaN    NaN
322854921  268656901  0      NaN   NaN    NaN      NaN    NaN    NaN
           10602410   0      NaN   NaN    NaN      NaN    NaN    NaN
           322854916  0      NaN   NaN    NaN      NaN    NaN    NaN
10602410   3212415597 0      NaN   NaN    NaN      NaN    NaN    NaN
           10602396   0    L 143   NaN    NaN      NaN    NaN    NaN
           322854921  0      NaN   NaN    NaN      NaN    NaN    NaN
10602396   268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
           3328610208 0    L 143   NaN    NaN      NaN    NaN    NaN
           20909583   0      NaN   NaN    NaN      NaN    NaN    NaN
3328610208 3328610212 0      NaN   NaN    NaN      NaN    NaN    NaN
           3328610215 0    L 143   NaN    NaN      NaN    NaN    NaN
3328610215 3328610218 0    L 143   NaN    NaN      NaN    NaN    NaN
           3328610212 0      NaN   NaN    NaN      NaN    NaN    NaN
3328610218 20909586   0      NaN   NaN    NaN      NaN    NaN    NaN
           20909587   0    L 143   NaN    NaN      NaN    NaN    NaN
20909587   1620783442 0      NaN   NaN    NaN      NaN    NaN    NaN
           206265755  0    L 143   NaN    NaN      NaN    NaN    NaN
206265755  206178456  0    L 143   NaN    NaN      NaN    NaN    NaN
206178456  206178458  0      NaN   NaN    NaN      NaN    NaN    NaN
           60365099   0    L 143   NaN    NaN      NaN    NaN    NaN
60365099   60365459   0    L 143   NaN    NaN      NaN    NaN    NaN
           60365100   0     B 49   NaN    NaN      NaN    NaN    NaN
60365100   20834070   0      NaN   NaN    NaN      NaN    NaN    NaN
           300014888  0     B 49   NaN    NaN      NaN    NaN    NaN

In [22]:
#df_edge[0]['v']

In [23]:
#df.loc['London', 'Day'].loc['2019-07-01'] --- multilevel index



df_edge.loc[route[0],:].loc[route[1]]
#idx = pd.Index(df_edge) 
##val = df_edge.loc[route[0],:]
#val

,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry,ref,width,bridge,junction,access,tunnel
key,,,,,,,,,,,,,,,
0,22959075,False,NaN,Wechselstraße,living_street,False,61.715,NaN,"LINESTRING (6.63906 49.75107, 6.63911 49.75103...",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_edge

In [24]:
df_edge.loc[route[0],:]

,,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry,ref,width,bridge,junction,access,tunnel
v,key,,,,,,,,,,,,,,,
20909623,0,6073629,True,NaN,Gervasiusstraße,residential,False,92.770,50,"LINESTRING (6.63906 49.75107, 6.63913 49.75115...",NaN,NaN,NaN,NaN,NaN,NaN
1428980932,0,22959075,False,NaN,Wechselstraße,living_street,False,61.715,NaN,"LINESTRING (6.63906 49.75107, 6.63911 49.75103...",NaN,NaN,NaN,NaN,NaN,NaN

In [186]:
route

[268656889,
 1428980932,
 1428980910,
 322854916,
 322854921,
 10602410,
 10602396,
 3328610208,
 3328610215,
 3328610218,
 20909587,
 206265755,
 206178456,
 60365099,
 60365100]

In [189]:
route
new_route = route[0:]
print(new_route)

[268656889, 1428980932, 1428980910, 322854916, 322854921, 10602410, 10602396, 3328610208, 3328610215, 3328610218, 20909587, 206265755, 206178456, 60365099, 60365100]

In [25]:
print(orig)
print(dest)

268656889
60365100

In [ ]:
for i in df_edge:
    var = df_edge
    print(var)

In [ ]:
for index, row in df_edge.iterrows():
    print(row['name'])
    print(type(index))

In [190]:
new_df = gdp.GeoDataFrame(data=None, index=None, columns=['source', 'destination','osmid', 'oneway', 'lanes', 'name', 'highway', 'reversed', 'length',
       'maxspeed', 'geometry'])
c = 0
new_orig = orig
new_dest = dest
get_u = 0
get_v = 0
temp = 'NaN'
#,df_edge.loc[index[0],:].loc[index[1]],
for i in new_route:
    # node = u, under that node there is multiple node as v --- accessing the v
    #print(i)
    for index, j in df_edge.iterrows():
            if index[0] == new_orig and index[1] == i:
                src = index[0]
                dest = index[1]
                osmid = j['osmid']
                one_way = j['oneway']
                lanes = j['lanes']
                #print(max(int(lanes)))
                name = j['name']
                highway = j['highway']
                reveresed = j['reversed']
                length = j['length']
                max_speed = j['maxspeed'] 
                geometry = j['geometry']
                new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
                                        'maxspeed' : max_speed, 'geometry' : geometry}, ignore_index=True)
    new_orig = i 

#new_df = new_df.append(df_edge.loc[new_orig,:].loc[new_dest])

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\3899555951.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\pandas\core\dtypes\cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)

In [28]:
new_df

,source,destination,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry
0,268656889,1428980932,22959075,False,NaN,Wechselstraße,living_street,False,61.715,NaN,"LINESTRING (6.63906 49.75107, 6.63911 49.75103..."
1,1428980932,1428980910,129534324,False,NaN,Kuhnenstraße,living_street,False,44.524,NaN,"LINESTRING (6.63983 49.75084, 6.63964 49.75046)"
2,1428980910,322854916,461707736,False,NaN,Kuhnenstraße,living_street,True,64.006,NaN,"LINESTRING (6.63964 49.75046, 6.64028 49.75029..."
3,322854916,322854921,"[928536690, 814112811]",False,2,Weberbach,residential,False,37.408,50,"LINESTRING (6.64047 49.75025, 6.64044 49.75019..."
4,322854921,10602410,329619113,False,NaN,Weberbach,residential,False,47.082,50,"LINESTRING (6.64033 49.74993, 6.64022 49.74969..."
5,10602410,10602396,"[348744826, 44181036]",True,3,Kaiserstraße,secondary,False,219.652,50,"LINESTRING (6.64015 49.74952, 6.64005 49.74955..."
6,10602396,3328610208,44503497,True,NaN,Kaiserstraße,secondary,False,153.907,50,"LINESTRING (6.63723 49.75009, 6.63711 49.75012..."
7,3328610208,3328610215,484936170,True,NaN,Kaiserstraße,secondary,False,24.475,50,"LINESTRING (6.63514 49.75040, 6.63495 49.75043..."
8,3328610215,3328610218,449537987,True,NaN,Kaiserstraße,secondary,False,11.676,50,"LINESTRING (6.63481 49.75045, 6.63465 49.75047)"
9,3328610218,20909587,"[396347959, 43176479]",True,"[2, 3]",Kaiserstraße,secondary,False,232.15,50,"LINESTRING (6.63465 49.75047, 6.63439 49.75050..."
10,20909587,206265755,"[793427594, 161279663]",True,3,Kaiserstraße,secondary,False,144.406,50,"LINESTRING (6.63148 49.75089, 6.63136 49.75090..."
11,206265755,206178456,391065024,True,3,Kaiserstraße,secondary,False,65.492,50,"LINESTRING (6.62952 49.75116, 6.62929 49.75118..."
12,206178456,60365099,391065027,True,3,Kaiserstraße,secondary,False,24.128,50,"LINESTRING (6.62862 49.75128, 6.62843 49.75130..."
13,60365099,60365100,177395531,True,2,Johanniterufer,primary,False,59.961,50,"LINESTRING (6.62829 49.75129, 6.62829 49.75134..."

In [ ]:
# for identifying nan
print(new_df[new_df['maxspeed'].isnull()])

In [ ]:
for index, j in new_df.iterrows():
   #print(j['lanes'], type(j['lanes'])) --- float = nan , str = number, list = [2, 3]
   #if type(j['lanes'] == 'float'):
   print(j['lanes'])

In [31]:
#new_df['maxspeed'] = new_df['maxspeed'].astype(str).astype(int)
new_df['maxspeed'] = new_df['maxspeed'].astype('Int64')

In [32]:
new_df['maxspeed'].mean()

50.0

In [33]:
mean_value = new_df['maxspeed'].mean()
new_df['maxspeed'].fillna(int(mean_value), inplace = True)

In [34]:
new_df

,source,destination,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry
0,268656889,1428980932,22959075,False,NaN,Wechselstraße,living_street,False,61.715,50,"LINESTRING (6.63906 49.75107, 6.63911 49.75103..."
1,1428980932,1428980910,129534324,False,NaN,Kuhnenstraße,living_street,False,44.524,50,"LINESTRING (6.63983 49.75084, 6.63964 49.75046)"
2,1428980910,322854916,461707736,False,NaN,Kuhnenstraße,living_street,True,64.006,50,"LINESTRING (6.63964 49.75046, 6.64028 49.75029..."
3,322854916,322854921,"[928536690, 814112811]",False,2,Weberbach,residential,False,37.408,50,"LINESTRING (6.64047 49.75025, 6.64044 49.75019..."
4,322854921,10602410,329619113,False,NaN,Weberbach,residential,False,47.082,50,"LINESTRING (6.64033 49.74993, 6.64022 49.74969..."
5,10602410,10602396,"[348744826, 44181036]",True,3,Kaiserstraße,secondary,False,219.652,50,"LINESTRING (6.64015 49.74952, 6.64005 49.74955..."
6,10602396,3328610208,44503497,True,NaN,Kaiserstraße,secondary,False,153.907,50,"LINESTRING (6.63723 49.75009, 6.63711 49.75012..."
7,3328610208,3328610215,484936170,True,NaN,Kaiserstraße,secondary,False,24.475,50,"LINESTRING (6.63514 49.75040, 6.63495 49.75043..."
8,3328610215,3328610218,449537987,True,NaN,Kaiserstraße,secondary,False,11.676,50,"LINESTRING (6.63481 49.75045, 6.63465 49.75047)"
9,3328610218,20909587,"[396347959, 43176479]",True,"[2, 3]",Kaiserstraße,secondary,False,232.15,50,"LINESTRING (6.63465 49.75047, 6.63439 49.75050..."
10,20909587,206265755,"[793427594, 161279663]",True,3,Kaiserstraße,secondary,False,144.406,50,"LINESTRING (6.63148 49.75089, 6.63136 49.75090..."
11,206265755,206178456,391065024,True,3,Kaiserstraße,secondary,False,65.492,50,"LINESTRING (6.62952 49.75116, 6.62929 49.75118..."
12,206178456,60365099,391065027,True,3,Kaiserstraße,secondary,False,24.128,50,"LINESTRING (6.62862 49.75128, 6.62843 49.75130..."
13,60365099,60365100,177395531,True,2,Johanniterufer,primary,False,59.961,50,"LINESTRING (6.62829 49.75129, 6.62829 49.75134..."

In [35]:
max(new_df['lanes'][9])

'3'

In [36]:
df_edge.index.get_level_values('u')[4] # first level index 'u' from edge data set

1428980932

In [37]:
df_edge.index.get_level_values('v') # second level index 'v' from edge data set

Int64Index([  20909623, 1428980932,   20909627, 1428980910,  268656889,
            1428980932,  322854916,  268656888, 1428980910,  322854921,
            3325983705,  268656901,   10602410,  322854916, 3212415597,
              10602396,  322854921,  268656889, 3328610208,   20909583,
            3328610212, 3328610215, 3328610218, 3328610212,   20909586,
              20909587, 1620783442,  206265755,  206178456,  206178458,
              60365099,   60365459,   60365100,   20834070,  300014888],
           dtype='int64', name='v')

In [40]:
node_df.index.get_level_values('osmid')

Int64Index([ 268656889, 1428980932, 1428980910,  322854916,  322854921,
              10602410,   10602396, 3328610208, 3328610215, 3328610218,
              20909587,  206265755,  206178456,   60365099,   60365100],
           dtype='int64', name='osmid')

In [41]:
df_edge.columns

Index(['osmid', 'oneway', 'lanes', 'name', 'highway', 'reversed', 'length',
       'maxspeed', 'geometry', 'ref', 'width', 'bridge', 'junction', 'access',
       'tunnel'],
      dtype='object')

In [ ]:
for i in route:
    print(gdf_edges.loc[(i, slice(None), slice(None)),:])

#### Traffic resillience / servicability index

In [156]:
# downloding the street network
place = "Trier, Germany"
#cf = '["highway"~"motorway"]'
#cf =  '["highway"~"primary"]'
#G = ox.graph_from_place("Trier, Germany", network_type= "drive") ### graph of the given city
G = ox.graph_from_place(place, network_type="drive")

In [157]:
## 1. convert the graph to geodataframe 
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

In [163]:
# impute speed on all edges missing data
G = ox.add_edge_speeds(G)

# calculate travel time (seconds) for all edges
G = ox.add_edge_travel_times(G)

In [164]:
# we have gdf_edges, gdf_nodes of Triers drivable roads

### lets find shortest path for non degreded situation for arbitrarily selected source and destination

def shortest_path(origin, destination, G):
    x_orig = origin['lat']
    y_origin = origin['lon']
    x_dest = destination['lat']
    y_dest = destination['lon']
    orig = ox.distance.nearest_nodes(G, X = x_orig, Y = y_origin) # saarstraße
    dest = ox.distance.nearest_nodes(G, X = x_dest, Y = y_dest) # germanstraße, gervasiusstraße
    route = ox.shortest_path(G, orig, dest, weight = "travel_time")
    m = ox.plot_route_folium(G, route, weight=10)
    filepath = r'C:\Users\looka\OneDrive\Desktop\RCS\shortest_1.html'
    m.save(filepath)
    IFrame(filepath, width=600, height = 500)
    return route

In [165]:
type(route)

list

In [166]:

origin = {'lat': 6.639066, 'lon': 49.751096}
destination = {'lat': 6.628289, 'lon': 49.751833}

short_route = shortest_path(origin, destination, G)

In [167]:
route_length = int(sum(ox.utils_graph.get_route_edge_attributes(G, short_route, "length")))
route_travel_time  =  int(sum(ox.utils_graph.get_route_edge_attributes(G, short_route, "travel_time")))

In [168]:
route_length

1194

In [169]:
route_travel_time

97

In [171]:
short_route

[268656889,
 1428980932,
 20909627,
 3325983705,
 322854916,
 322854921,
 10602410,
 10602396,
 3328610208,
 3328610215,
 3328610218,
 20909587,
 206265755,
 206178456,
 60365099,
 60365100]

In [172]:
# getting the nodes of non degreded shortest route
def get_nodes(short_route):
    node_df = gdp.GeoDataFrame()
    for i in short_route:
        node_df = node_df.append((gdf_nodes.loc[[i]]))
    return node_df

In [173]:
nodes = get_nodes(short_route)
nodes

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))

,y,x,street_count,highway,ref,geometry
osmid,,,,,,
268656889,49.751074,6.639062,4,NaN,NaN,POINT (6.63906 49.75107)
1428980932,49.750844,6.639827,3,NaN,NaN,POINT (6.63983 49.75084)
20909627,49.750787,6.640100,3,NaN,NaN,POINT (6.64010 49.75079)
3325983705,49.750668,6.640676,3,NaN,NaN,POINT (6.64068 49.75067)
322854916,49.750250,6.640466,3,NaN,NaN,POINT (6.64047 49.75025)
322854921,49.749926,6.640325,3,NaN,NaN,POINT (6.64033 49.74993)
10602410,49.749518,6.640148,4,NaN,NaN,POINT (6.64015 49.74952)
10602396,49.750094,6.637228,4,NaN,NaN,POINT (6.63723 49.75009)
3328610208,49.750404,6.635141,3,NaN,NaN,POINT (6.63514 49.75040)
3328610215,49.750447,6.634806,4,NaN,NaN,POINT (6.63481 49.75045)
3328610218,49.750467,6.634647,4,NaN,NaN,POINT (6.63465 49.75047)
20909587,49.750887,6.631482,4,NaN,NaN,POINT (6.63148 49.75089)
206265755,49.751156,6.629516,3,NaN,NaN,POINT (6.62952 49.75116)
206178456,49.751275,6.628623,3,NaN,NaN,POINT (6.62862 49.75128)
60365099,49.751293,6.628291,4,NaN,NaN,POINT (6.62829 49.75129)
60365100,49.751830,6.628266,4,NaN,NaN,POINT (6.62827 49.75183)

In [174]:
# getting the edges of non degreded shortest route
def get_edges(short_route):
    edge_df = gdp.GeoDataFrame()
    for i in short_route:
        edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
    return edge_df

In [175]:
edges = get_edges(short_route)
edges

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])

                                            osmid  oneway   lanes  \
u          v          key
268656889  20909623   0                   6073629    True     NaN
           1428980932 0                  22959075   False     NaN
1428980932 20909627   0                  22959075   False     NaN
           1428980910 0                 129534324   False     NaN
           268656889  0                  22959075   False     NaN
20909627   4191116522 0                   6073632   False     NaN
           1428980932 0                  22959075   False     NaN
           3325983705 0                  22959075   False     NaN
3325983705 20909627   0                  22959075   False     NaN
           322854916  0                 814112811   False       2
           20909628   0                 814112811   False       2
322854916  1428980910 0                 461707736   False     NaN
           322854921  0    [928536690, 814112811]   False       2
           3325983705 0                 814112811   False       2
322854921  268656901  0                  24718036   False     NaN
           10602410   0                 329619113   False     NaN
           322854916  0    [928536690, 814112811]   False       2
10602410   3212415597 0                   6073363   False     NaN
           10602396   0     [348744826, 44181036]    True       3
           322854921  0                 329619113   False     NaN
10602396   268656889  0      [620480498, 6073765]    True       1
           3328610208 0                  44503497    True     NaN
           20909583   0                 113363975    True       1
3328610208 3328610212 0                 326240046    True     NaN
           3328610215 0                 484936170    True     NaN
3328610215 3328610218 0                 449537987    True     NaN
           3328610212 0                 348744824    True     NaN
3328610218 20909586   0                   6073647    True       2
           20909587   0     [396347959, 43176479]    True  [2, 3]
20909587   1620783442 0     [201864952, 23323565]   False       2
           206265755  0    [793427594, 161279663]    True       3
206265755  206178456  0                 391065024    True       3
206178456  206178458  0                  19789570    True       1
           60365099   0                 391065027    True       3
60365099   60365459   0                 396347958    True       2
           60365100   0                 177395531    True       2
60365100   20834070   0                  39177136    True       1
           300014888  0                  44841066    True       2

                                                name  \
u          v          key
268656889  20909623   0              Gervasiusstraße
           1428980932 0                Wechselstraße
1428980932 20909627   0                Wechselstraße
           1428980910 0                 Kuhnenstraße
           268656889  0                Wechselstraße
20909627   4191116522 0                 Rahnenstraße
           1428980932 0                Wechselstraße
           3325983705 0                Wechselstraße
3325983705 20909627   0                Wechselstraße
           322854916  0                    Weberbach
           20909628   0                    Weberbach
322854916  1428980910 0                 Kuhnenstraße
           322854921  0                    Weberbach
           3325983705 0                    Weberbach
322854921  268656901  0                    Graugasse
           10602410   0                    Weberbach
           322854916  0                    Weberbach
10602410   3212415597 0                          NaN
           10602396   0                 Kaiserstraße
           322854921  0                    Weberbach
10602396   268656889  0    [Germanstraße, Neustraße]
           3328610208 0                 Kaiserstraße
           20909583   0                          NaN
3328610208 3328610212 0           Gerty-Spies-Straße
           3328610215 0                 Kaiserstraße
3328610215 3328610218 0                 Kaiserstraße
           3328610212 0           Gerty-Spies-Straße
3328610218 20909586   0                          NaN
           20909587   0                 Kaiserstraße
20909587   1620783442 0        Lorenz-Kellner-Straße
           206265755  0                 Kaiserstraße
206265755  206178456  0                 Kaiserstraße
206178456  206178458  0                          NaN
           60365099   0                 Kaiserstraße
60365099   60365459   0                 Kaiserstraße
           60365100   0               Johanniterufer
60365100   20834070   0             Karl-Marx-Straße
           300014888  0               Johanniterufer

                                                highway reversed   length  \
u          v          key
268656889  20909623   0                     residential    False   92.770
           1428980932 0                   living_street    False   61.715
1428980932 20909627   0                   living_street    False   20.646
           1428980910 0                   living_street    False   44.524
           268656889  0                   living_street     True   61.715
20909627   4191116522 0                   living_street    False   37.013
           1428980932 0                   living_street     True   20.646
           3325983705 0                   living_street    False   43.376
3325983705 20909627   0                   living_street     True   43.376
           322854916  0                     residential    False   48.905
           20909628   0                     residential     True   99.896
322854916  1428980910 0                   living_street    False   64.006
           322854921  0                     residential    False   37.408
           3325983705 0                     residential     True   48.905
322854921  268656901  0                   living_street     True  125.374
           10602410   0                     residential    False   47.082
           322854916  0                     residential     True   37.408
10602410   3212415597 0                     residential    False   28.040
           10602396   0                       secondary    False  219.652
           322854921  0                     residential     True   47.082
10602396   268656889  0    [residential, living_street]    False  249.956
           3328610208 0                       secondary    False  153.907
           20909583   0                  secondary_link    False   36.470
3328610208 3328610212 0                     residential    False   30.219
           3328610215 0                       secondary    False   24.475
3328610215 3328610218 0                       secondary    False   11.676
           3328610212 0                     residential    False   19.963
3328610218 20909586   0                     residential    False   45.665
           20909587   0                       secondary    False  232.150
20909587   1620783442 0                     residential    False  132.964
           206265755  0                       secondary    False  144.406
206265755  206178456  0                       secondary    False   65.492
206178456  206178458  0                  secondary_link    False   42.055
           60365099   0                       secondary    False   24.128
60365099   60365459   0                       secondary    False   12.063
           60365100   0                         primary    False   59.961
60365100   20834070   0                    unclassified    False   11.915
           300014888  0                         primary    False  106.307

                          maxspeed  \
u          v          key
268656889  20909623   0         50
           1428980932 0        NaN
1428980932 20909627   0        NaN
           1428980910 0        NaN
           268656889  0        NaN
20909627   4191116522 0        NaN
           1428980932 0        NaN
           3325983705 0        NaN
3325983705 20909627   0        NaN
           322854916  0         50
           20909628   0         50
322854916  1428980910 0        NaN
           322854921  0         50
           3325983705 0         50
322854921  268656901  0        NaN
           10602410   0         50
           322854916  0         50
10602410   3212415597 0        NaN
           10602396   0         50
           322854921  0         50
10602396   268656889  0         50
           3328610208 0         50
           20909583   0         50
3328610208 3328610212 0        NaN
           3328610215 0         50
3328610215 3328610218 0         50
           3328610212 0        NaN
3328610218 20909586   0         50
           20909587   0         50
20909587   1620783442 0        NaN
           206265755  0         50
206265755  206178456  0         50
206178456  206178458  0         50
           60365099   0         50
60365099   60365459   0         50
           60365100   0         50
60365100   20834070   0         50
           300014888  0         50

                                                                    geometry  \
u          v          key
268656889  20909623   0    LINESTRING (6.63906 49.75107, 6.63913 49.75115...
           1428980932 0    LINESTRING (6.63906 49.75107, 6.63911 49.75103...
1428980932 20909627   0      LINESTRING (6.63983 49.75084, 6.64010 49.75079)
           1428980910 0      LINESTRING (6.63983 49.75084, 6.63964 49.75046)
           268656889  0    LINESTRING (6.63983 49.75084, 6.63940 49.75093...
20909627   4191116522 0      LINESTRING (6.64010 49.75079, 6.64029 49.75110)
           1428980932 0      LINESTRING (6.64010 49.75079, 6.63983 49.75084)
           3325983705 0    LINESTRING (6.64010 49.75079, 6.64023 49.75076...
3325983705 20909627   0    LINESTRING (6.64068 49.75067, 6.64053 49.75070...
           322854916  0    LINESTRING (6.64068 49.75067, 6.64058 49.75047...
           20909628   0    LINESTRING (6.64068 49.75067, 6.64071 49.75075...
322854916  1428980910 0    LINESTRING (6.64047 49.75025, 6.64035 49.75027...
           322854921  0    LINESTRING (6.64047 49.75025, 6.64044 49.75019...
           3325983705 0    LINESTRING (6.64047 49.75025, 6.64058 49.75047...
322854921  268656901  0    LINESTRING (6.64033 49.74993, 6.64019 49.74994...
           10602410   0    LINESTRING (6.64033 49.74993, 6.64022 49.74969...
           322854916  0    LINESTRING (6.64033 49.74993, 6.64044 49.75019...
10602410   3212415597 0    LINESTRING (6.64015 49.74952, 6.64008 49.74938...
           10602396   0    LINESTRING (6.64015 49.74952, 6.64005 49.74955...
           322854921  0    LINESTRING (6.64015 49.74952, 6.64020 49.74964...
10602396   268656889  0    LINESTRING (6.63723 49.75009, 6.63724 49.75015...
           3328610208 0    LINESTRING (6.63723 49.75009, 6.63711 49.75012...
           20909583   0    LINESTRING (6.63723 49.75009, 6.63717 49.75006...
3328610208 3328610212 0    LINESTRING (6.63514 49.75040, 6.63502 49.75046...
           3328610215 0    LINESTRING (6.63514 49.75040, 6.63495 49.75043...
3328610215 3328610218 0      LINESTRING (6.63481 49.75045, 6.63465 49.75047)
           3328610212 0    LINESTRING (6.63481 49.75045, 6.63483 49.75049...
3328610218 20909586   0    LINESTRING (6.63465 49.75047, 6.63460 49.75044...
           20909587   0    LINESTRING (6.63465 49.75047, 6.63439 49.75050...
20909587   1620783442 0    LINESTRING (6.63148 49.75089, 6.63152 49.75096...
           206265755  0    LINESTRING (6.63148 49.75089, 6.63136 49.75090...
206265755  206178456  0    LINESTRING (6.62952 49.75116, 6.62929 49.75118...
206178456  206178458  0    LINESTRING (6.62862 49.75128, 6.62854 49.75123...
           60365099   0    LINESTRING (6.62862 49.75128, 6.62843 49.75130...
60365099   60365459   0      LINESTRING (6.62829 49.75129, 6.62814 49.75124)
           60365100   0    LINESTRING (6.62829 49.75129, 6.62829 49.75134...
60365100   20834070   0      LINESTRING (6.62827 49.75183, 6.62810 49.75181)
           300014888  0    LINESTRING (6.62827 49.75183, 6.62827 49.75188...

                             ref width bridge junction access tunnel
u          v          key
268656889  20909623   0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980932 0      NaN   NaN    NaN      NaN    NaN    NaN
1428980932 20909627   0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980910 0      NaN   NaN    NaN      NaN    NaN    NaN
           268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
20909627   4191116522 0      NaN   NaN    NaN      NaN    NaN    NaN
           1428980932 0      NaN   NaN    NaN      NaN    NaN    NaN
           3325983705 0      NaN   NaN    NaN      NaN    NaN    NaN
3325983705 20909627   0      NaN   NaN    NaN      NaN    NaN    NaN
           322854916  0      NaN   NaN    NaN      NaN    NaN    NaN
           20909628   0      NaN   NaN    NaN      NaN    NaN    NaN
322854916  1428980910 0      NaN   NaN    NaN      NaN    NaN    NaN
           322854921  0      NaN   NaN    NaN      NaN    NaN    NaN
           3325983705 0      NaN   NaN    NaN      NaN    NaN    NaN
322854921  268656901  0      NaN   NaN    NaN      NaN    NaN    NaN
           10602410   0      NaN   NaN    NaN      NaN    NaN    NaN
           322854916  0      NaN   NaN    NaN      NaN    NaN    NaN
10602410   3212415597 0      NaN   NaN    NaN      NaN    NaN    NaN
           10602396   0    L 143   NaN    NaN      NaN    NaN    NaN
           322854921  0      NaN   NaN    NaN      NaN    NaN    NaN
10602396   268656889  0      NaN   NaN    NaN      NaN    NaN    NaN
           3328610208 0    L 143   NaN    NaN      NaN    NaN    NaN
           20909583   0      NaN   NaN    NaN      NaN    NaN    NaN
3328610208 3328610212 0      NaN   NaN    NaN      NaN    NaN    NaN
           3328610215 0    L 143   NaN    NaN      NaN    NaN    NaN
3328610215 3328610218 0    L 143   NaN    NaN      NaN    NaN    NaN
           3328610212 0      NaN   NaN    NaN      NaN    NaN    NaN
3328610218 20909586   0      NaN   NaN    NaN      NaN    NaN    NaN
           20909587   0    L 143   NaN    NaN      NaN    NaN    NaN
20909587   1620783442 0      NaN   NaN    NaN      NaN    NaN    NaN
           206265755  0    L 143   NaN    NaN      NaN    NaN    NaN
206265755  206178456  0    L 143   NaN    NaN      NaN    NaN    NaN
206178456  206178458  0      NaN   NaN    NaN      NaN    NaN    NaN
           60365099   0    L 143   NaN    NaN      NaN    NaN    NaN
60365099   60365459   0    L 143   NaN    NaN      NaN    NaN    NaN
           60365100   0     B 49   NaN    NaN      NaN    NaN    NaN
60365100   20834070   0      NaN   NaN    NaN      NaN    NaN    NaN
           300014888  0     B 49   NaN    NaN      NaN    NaN    NaN

### if edge are degraded

In [176]:
# simplify the dataset
def dataset(edges):       
    new_df = gdp.GeoDataFrame(data=None, index=None, columns=['source', 'destination','osmid', 'oneway', 'lanes', 'name', 'highway', 'reversed', 'length',
            'maxspeed', 'geometry'])
    c = 0
    new_orig = orig
    new_dest = dest
    get_u = 0
    get_v = 0
    temp = 'NaN'
    #,df_edge.loc[index[0],:].loc[index[1]],
    for i in edges:
        # node = u, under that node there is multiple node as v --- accessing the v
        #print(i)
        for index, j in edges.iterrows():
                if index[0] == new_orig and index[1] == i:
                    src = index[0]
                    dest = index[1]
                    osmid = j['osmid']
                    one_way = j['oneway']
                    lanes = j['lanes']
                    #print(max(int(lanes)))
                    name = j['name']
                    highway = j['highway']
                    reveresed = j['reversed']
                    length = j['length']
                    max_speed = j['maxspeed'] 
                    geometry = j['geometry']
                    new_df = new_df.append({'source' : src, 'destination' : dest, 'osmid' : osmid, 'oneway': one_way, 'lanes' : lanes, 'name' : name, 'highway' : highway, 'reversed' : reveresed, 'length' : length,
                                                'maxspeed' : max_speed, 'geometry' : geometry}, ignore_index=True)
        new_orig = i
    return new_df

In [177]:
new_df = dataset(edges)

,source,destination,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry
0,268656889,1428980932,22959075,False,NaN,Wechselstraße,living_street,False,61.715,50,"LINESTRING (6.63906 49.75107, 6.63911 49.75103..."
1,1428980932,1428980910,129534324,False,NaN,Kuhnenstraße,living_street,False,44.524,50,"LINESTRING (6.63983 49.75084, 6.63964 49.75046)"
2,1428980910,322854916,461707736,False,NaN,Kuhnenstraße,living_street,True,64.006,50,"LINESTRING (6.63964 49.75046, 6.64028 49.75029..."
3,322854916,322854921,"[928536690, 814112811]",False,2,Weberbach,residential,False,37.408,50,"LINESTRING (6.64047 49.75025, 6.64044 49.75019..."
4,322854921,10602410,329619113,False,NaN,Weberbach,residential,False,47.082,50,"LINESTRING (6.64033 49.74993, 6.64022 49.74969..."
5,10602410,10602396,"[348744826, 44181036]",True,3,Kaiserstraße,secondary,False,219.652,50,"LINESTRING (6.64015 49.74952, 6.64005 49.74955..."
6,10602396,3328610208,44503497,True,NaN,Kaiserstraße,secondary,False,153.907,50,"LINESTRING (6.63723 49.75009, 6.63711 49.75012..."
7,3328610208,3328610215,484936170,True,NaN,Kaiserstraße,secondary,False,24.475,50,"LINESTRING (6.63514 49.75040, 6.63495 49.75043..."
8,3328610215,3328610218,449537987,True,NaN,Kaiserstraße,secondary,False,11.676,50,"LINESTRING (6.63481 49.75045, 6.63465 49.75047)"
9,3328610218,20909587,"[396347959, 43176479]",True,"[2, 3]",Kaiserstraße,secondary,False,232.15,50,"LINESTRING (6.63465 49.75047, 6.63439 49.75050..."
10,20909587,206265755,"[793427594, 161279663]",True,3,Kaiserstraße,secondary,False,144.406,50,"LINESTRING (6.63148 49.75089, 6.63136 49.75090..."
11,206265755,206178456,391065024,True,3,Kaiserstraße,secondary,False,65.492,50,"LINESTRING (6.62952 49.75116, 6.62929 49.75118..."
12,206178456,60365099,391065027,True,3,Kaiserstraße,secondary,False,24.128,50,"LINESTRING (6.62862 49.75128, 6.62843 49.75130..."
13,60365099,60365100,177395531,True,2,Johanniterufer,primary,False,59.961,50,"LINESTRING (6.62829 49.75129, 6.62829 49.75134..."

In [178]:
new_df.loc[(0),:]['source']

268656889

In [179]:
i = 1
select_edge = edges.loc[(new_df.loc[(i),:]['source'], new_df.loc[(i),:]['destination'], slice(None)),:]
select_edge

,,,osmid,oneway,lanes,name,highway,reversed,length,maxspeed,geometry,ref,width,bridge,junction,access,tunnel
u,v,key,,,,,,,,,,,,,,,
1428980932,1428980910,0,129534324,False,NaN,Kuhnenstraße,living_street,False,44.524,NaN,"LINESTRING (6.63983 49.75084, 6.63964 49.75046)",NaN,NaN,NaN,NaN,NaN,NaN

In [180]:
len(new_df)

14

In [181]:
new_gdf_edges = gdf_edges.copy(deep=True)
new_gdf_nodes = gdf_nodes.copy(deep=True)

In [ ]:
# # compare the two routes
# route1_length = int(sum(ox.utils_graph.get_route_edge_attributes(G, route1, "length")))
# route2_length = int(sum(ox.utils_graph.get_route_edge_attributes(G, route2, "length")))
# route1_time = int(sum(ox.utils_graph.get_route_edge_attributes(G, route1, "travel_time")))
# route2_time = int(sum(ox.utils_graph.get_route_edge_attributes(G, route2, "travel_time")))
# print("Route 1 is", route1_length, "meters and takes", route1_time, "seconds.")
# print("Route 2 is", route2_length, "meters and takes", route2_time, "seconds.")

In [182]:
paths_data = gdp.GeoDataFrame(data=None, index=None, columns=['source', 'destination','route_length(meters)', 'travel_time(seconds)', 'total_edges', 'total_nodes'])
# new_df is best route for non degreded situation

# intial route info enter into the paths data
route_length = int(sum(ox.utils_graph.get_route_edge_attributes(G, short_route, "length")))
route_travel_time  =  int(sum(ox.utils_graph.get_route_edge_attributes(G, short_route, "travel_time")))

paths_data  = paths_data.append({'source' : orig, 'destination' : dest, 'route_length(meters)': route_length, 
                                'travel_time(seconds)': route_travel_time, 'total_edges' : len(node_df) - 1, 'total_nodes' : len(node_df)}, ignore_index=True)

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\1124630662.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  paths_data  = paths_data.append({'source' : orig, 'destination' : dest, 'route_length(meters)': route_length,

In [183]:
paths_data

,source,destination,route_length(meters),travel_time(seconds),total_edges,total_nodes
0,268656889,60365100,1194,97,14,15

In [184]:
for i in range(len(new_df)):
    # select the degreded edge
    print('source: ',new_df.loc[(i),:]['source'])
    print('destination: ',new_df.loc[(i),:]['destination'])
    select_edge = edges.loc[(new_df.loc[(i),:]['source'], new_df.loc[(i),:]['destination'], slice(None)),:] # selecting the subedge from the route as degerded edge
    # drop the edge from gdf_edges
    new_gdf_edges = new_gdf_edges.drop(index=(new_df.loc[(1),:]['source'], new_df.loc[(1),:]['destination']))
    
    # create new graph from new edges and nodes
    new_G = ox.utils_graph.graph_from_gdfs(new_gdf_nodes, new_gdf_edges, graph_attrs=None)
    
    # impute speed on all edges missing data
    new_G = ox.add_edge_speeds(new_G)
    # calculate travel time (seconds) for all edges
    new_G = ox.add_edge_travel_times(new_G)

    #  convert graph to nodes and edges dataframe
    new_gdf_nodes, new_gdf_edges = ox.graph_to_gdfs(new_G)

    # again find the shortest route after missing the degreded edge
    new_short_path = shortest_path(origin, destination, new_G) #  new shortrest path actually represent route

    route_length = int(sum(ox.utils_graph.get_route_edge_attributes(new_G, new_short_path, "length")))
    route_travel_time  =  int(sum(ox.utils_graph.get_route_edge_attributes(new_G, new_short_path, "travel_time")))

    # get the nodes of new short path
    new_nodes = get_nodes(new_short_path)
    # get the edges of new short path
    new_edges = get_edges(new_short_path)

    paths_data  = paths_data.append({'source' : orig, 'destination' : dest, 'route_length(meters)': route_length,
                                     'travel_time(seconds)': route_travel_time, 'total_edges' : len(new_nodes) - 1, 'total_nodes' : len(new_nodes)}, ignore_index=True)

source:  268656889
destination:  1428980932

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\1589923834.py:7: PerformanceWarning: indexing past lexsort depth may impact performance.
  new_gdf_edges = new_gdf_edges.drop(index=(new_df.loc[(1),:]['source'], new_df.loc[(1),:]['destination']))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\4197316962.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  node_df = node_df.append((gdf_nodes.loc[[i]]))
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\2548484021.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  edge_df = edge_df.append(gdf_edges.loc[(i, slice(None), slice(None)),:])
C:\Users\looka\AppData\Local\Temp\ipykernel_9980\1589923834.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  paths_data  = paths_data.append({'source' : orig, 'destination' : dest, 'route_length(meters)': route_length,

source:  1428980932
destination:  1428980910

C:\Users\looka\AppData\Local\Temp\ipykernel_9980\1589923834.py:7: PerformanceWarning: indexing past lexsort depth may impact performance.
  new_gdf_edges = new_gdf_edges.drop(index=(new_df.loc[(1),:]['source'], new_df.loc[(1),:]['destination']))

KeyError: (1428980932, 1428980910)

In [185]:
paths_data

,source,destination,route_length(meters),travel_time(seconds),total_edges,total_nodes
0,268656889,60365100,1194,97,14,15
1,268656889,60365100,1194,97,15,16

In [ ]:
new_nodes

In [ ]:
new_edges

In [ ]:
#select_edge = gdf_edges.loc[(new_df.loc[(i),:]['source'], new_df.loc[(i),:]['destination'], slice(None)),:]
#print(select_edge)